/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opscalculator;

/**
 *
 * @author 22brobdani
 */
public class SwingCalc extends javax.swing.JFrame {

    /**
     * Creates new form SwingCalc
     */
    public SwingCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IntTF = new javax.swing.JTextField();
        DoubleTF = new javax.swing.JTextField();
        ClrI = new javax.swing.JButton();
        AI = new javax.swing.JButton();
        MI = new javax.swing.JButton();
        XI = new javax.swing.JButton();
        DI = new javax.swing.JButton();
        RI = new javax.swing.JButton();
        PowI = new javax.swing.JButton();
        PowD = new javax.swing.JButton();
        AD = new javax.swing.JButton();
        MD = new javax.swing.JButton();
        XD = new javax.swing.JButton();
        DD = new javax.swing.JButton();
        ClrD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DITF = new javax.swing.JTextField();
        DDTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        WarningTF = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jLabel1.setText("Opps Calculator ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 110, 28);

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        jLabel2.setText("Daniel Broberg");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(256, 11, 133, 28);
        getContentPane().add(IntTF);
        IntTF.setBounds(10, 61, 110, 20);
        getContentPane().add(DoubleTF);
        DoubleTF.setBounds(256, 61, 119, 20);

        ClrI.setText("Clr");
        ClrI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClrIActionPerformed(evt);
            }
        });
        getContentPane().add(ClrI);
        ClrI.setBounds(10, 390, 60, 23);

        AI.setText("+=");
        AI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIActionPerformed(evt);
            }
        });
        getContentPane().add(AI);
        AI.setBounds(10, 144, 60, 23);

        MI.setText("-=");
        MI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIActionPerformed(evt);
            }
        });
        getContentPane().add(MI);
        MI.setBounds(10, 180, 60, 23);

        XI.setText("X=");
        XI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XIActionPerformed(evt);
            }
        });
        getContentPane().add(XI);
        XI.setBounds(10, 226, 60, 23);

        DI.setText("/=");
        DI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIActionPerformed(evt);
            }
        });
        getContentPane().add(DI);
        DI.setBounds(10, 267, 60, 23);

        RI.setText("%=");
        RI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIActionPerformed(evt);
            }
        });
        getContentPane().add(RI);
        RI.setBounds(10, 308, 60, 23);

        PowI.setText("Pow");
        PowI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowIActionPerformed(evt);
            }
        });
        getContentPane().add(PowI);
        PowI.setBounds(10, 349, 60, 23);

        PowD.setText("Pow");
        PowD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowDActionPerformed(evt);
            }
        });
        getContentPane().add(PowD);
        PowD.setBounds(256, 308, 60, 23);

        AD.setText("+=");
        AD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADActionPerformed(evt);
            }
        });
        getContentPane().add(AD);
        AD.setBounds(256, 144, 60, 23);

        MD.setText("-=");
        MD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDActionPerformed(evt);
            }
        });
        getContentPane().add(MD);
        MD.setBounds(256, 185, 60, 23);

        XD.setText("X=");
        XD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XDActionPerformed(evt);
            }
        });
        getContentPane().add(XD);
        XD.setBounds(256, 226, 60, 23);

        DD.setText("/=");
        DD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DDActionPerformed(evt);
            }
        });
        getContentPane().add(DD);
        DD.setBounds(256, 267, 60, 23);

        ClrD.setText("Clr");
        ClrD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClrDActionPerformed(evt);
            }
        });
        getContentPane().add(ClrD);
        ClrD.setBounds(260, 390, 60, 23);

        jLabel3.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 8)); // NOI18N
        jLabel3.setText("integer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 45, 40, 10);
        getContentPane().add(DITF);
        DITF.setBounds(10, 106, 110, 20);
        getContentPane().add(DDTF);
        DDTF.setBounds(256, 106, 119, 20);

        jLabel4.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 8)); // NOI18N
        jLabel4.setText("Delta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 29, 10);

        jLabel5.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 8)); // NOI18N
        jLabel5.setText("Double");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(256, 45, 39, 10);

        jLabel6.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 8)); // NOI18N
        jLabel6.setText("Delta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(256, 90, 29, 10);

        WarningTF.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 14)); // NOI18N
        getContentPane().add(WarningTF);
        WarningTF.setBounds(30, 430, 290, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       int sum = a + b;
       IntTF.setText(Integer.toString(sum));
       // TODO add your handling code here:
    }//GEN-LAST:event_AIActionPerformed

    private void MIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       int sum = a - b;
       IntTF.setText(Integer.toString(sum));
        // TODO add your handling code here:
    }//GEN-LAST:event_MIActionPerformed

    private void XIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       int sum = a * b;
       IntTF.setText(Integer.toString(sum));
        // TODO add your handling code here:
    }//GEN-LAST:event_XIActionPerformed

    private void DIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       if (b==0){
           WarningTF.setText("Are You Sure About That");
       }
       else{
       int sum = a / b;
       IntTF.setText(Integer.toString(sum));
       }
// TODO add your handling code here:
    }//GEN-LAST:event_DIActionPerformed

    private void RIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       if (b==0){
           WarningTF.setText("Are You Sure About That");
       }
       else{
       int sum = a % b;
       IntTF.setText(Integer.toString(sum));
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_RIActionPerformed

    private void PowIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowIActionPerformed
       String Tempa = IntTF.getText();
       String Tempb = DITF.getText();
       int a = Integer.parseInt(Tempa);
       int b = Integer.parseInt(Tempb);
       int sum = (int)Math.pow(a, b);
       IntTF.setText(Integer.toString(sum));
// TODO add your handling code here:
    }//GEN-LAST:event_PowIActionPerformed

    private void ClrIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClrIActionPerformed
        IntTF.setText("");
        DITF.setText("");   
        WarningTF.setText("");
    }//GEN-LAST:event_ClrIActionPerformed

    private void ADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADActionPerformed
       String Tempa = DoubleTF.getText();
       String Tempb = DDTF.getText();
       double a = Double.parseDouble(Tempa);
       double b = Double.parseDouble(Tempb);
       double sum = a+b;
       DoubleTF.setText(Double.toString(sum));        
    }//GEN-LAST:event_ADActionPerformed

    private void MDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDActionPerformed
       String Tempa = DoubleTF.getText();
       String Tempb = DDTF.getText();
       double a = Double.parseDouble(Tempa);
       double b = Double.parseDouble(Tempb);
       double sum = a-b;
       DoubleTF.setText(Double.toString(sum));
    }//GEN-LAST:event_MDActionPerformed

    private void XDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XDActionPerformed
       String Tempa = DoubleTF.getText();
       String Tempb = DDTF.getText();
       double a = Double.parseDouble(Tempa);
       double b = Double.parseDouble(Tempb);
       double sum = a*b;
       DoubleTF.setText(Double.toString(sum));
    }//GEN-LAST:event_XDActionPerformed

    private void DDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DDActionPerformed
       String Tempa = DoubleTF.getText();
       String Tempb = DDTF.getText();
       double a = Double.parseDouble(Tempa);
       double b = Double.parseDouble(Tempb);
       if (b==0){
           WarningTF.setText("Are You Sure About That");
       }
       else{
       double sum = a / b;
       DoubleTF.setText(Double.toString(sum));
       }
               
// TODO add your handling code here:
    }//GEN-LAST:event_DDActionPerformed

    private void PowDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowDActionPerformed
       String Tempa = DoubleTF.getText();
       String Tempb = DDTF.getText();
       double a = Double.parseDouble(Tempa);
       double b = Double.parseDouble(Tempb);
       double sum = (double)Math.pow(a, b);
       DoubleTF.setText(Double.toString(sum));
    }//GEN-LAST:event_PowDActionPerformed

    private void ClrDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClrDActionPerformed
       DoubleTF.setText("");
       DDTF.setText("");
       WarningTF.setText("");
    }//GEN-LAST:event_ClrDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AD;
    private javax.swing.JButton AI;
    private javax.swing.JButton ClrD;
    private javax.swing.JButton ClrI;
    private javax.swing.JButton DD;
    private javax.swing.JTextField DDTF;
    private javax.swing.JButton DI;
    private javax.swing.JTextField DITF;
    private javax.swing.JTextField DoubleTF;
    private javax.swing.JTextField IntTF;
    private javax.swing.JButton MD;
    private javax.swing.JButton MI;
    private javax.swing.JButton PowD;
    private javax.swing.JButton PowI;
    private javax.swing.JButton RI;
    private javax.swing.JLabel WarningTF;
    private javax.swing.JButton XD;
    private javax.swing.JButton XI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
