/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Flash
 */
import java.math.BigInteger;
public class ConverterFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConverterFrame
     */
    
    public ConverterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DecTF = new javax.swing.JTextField();
        BTF = new javax.swing.JTextField();
        HexTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Welcome to the Number Converter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 270, 30);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Decimal:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 80, 20);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Binary:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 50, 15);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Hexadecimal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 80, 20);

        DecTF.setBackground(new java.awt.Color(0, 0, 0));
        DecTF.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        DecTF.setForeground(new java.awt.Color(51, 255, 51));
        DecTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecTFActionPerformed(evt);
            }
        });
        getContentPane().add(DecTF);
        DecTF.setBounds(10, 90, 480, 20);

        BTF.setBackground(new java.awt.Color(0, 0, 0));
        BTF.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        BTF.setForeground(new java.awt.Color(51, 255, 51));
        BTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFActionPerformed(evt);
            }
        });
        getContentPane().add(BTF);
        BTF.setBounds(10, 160, 480, 20);

        HexTF.setBackground(new java.awt.Color(0, 0, 0));
        HexTF.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        HexTF.setForeground(new java.awt.Color(51, 255, 51));
        HexTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexTFActionPerformed(evt);
            }
        });
        getContentPane().add(HexTF);
        HexTF.setBounds(10, 230, 480, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/Black-background-photography-example.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFActionPerformed
        String TempA = BTF.getText();
        ConverterLogic a = new ConverterLogic();
        String Dec = a.BinaryToDec(TempA);
        String Hex = a.BinaryToHex(TempA);
        DecTF.setText(Dec);
        HexTF.setText(Hex);
    }//GEN-LAST:event_BTFActionPerformed

    private void HexTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexTFActionPerformed
        String TempA = HexTF.getText();
        ConverterLogic a = new ConverterLogic();
        String Dec = a.HexToDec(TempA);
        String Binary = a.HexToBinary(TempA);
        DecTF.setText(Dec);
        BTF.setText(Binary);
    }//GEN-LAST:event_HexTFActionPerformed

    private void DecTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecTFActionPerformed
        String TempA = DecTF.getText();
        ConverterLogic a = new ConverterLogic();
        String Binary = a.DecToBinary(TempA);
        String Hex = a.DecToHex(TempA);
        BTF.setText(Binary);
        HexTF.setText(Hex);
    }//GEN-LAST:event_DecTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BTF;
    private javax.swing.JTextField DecTF;
    private javax.swing.JTextField HexTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
